### ISSUE TITLE
link to demo

### ISSUE THREAD

**Issue by yoshuawuyts** [macropodhq/viewporter#8]
There was [a link](http://macropodhq.github.io/viewporter/) to the demo [in the slides](https://speakerdeck.com/ticky/viewport-trickery-v1-dot-1) but I couldn't find it on the repo. Might be cool to post it in url / README for others to discover :sparkles:. Thanks!

**Comment by ticky** [comment]
Good idea, fixed in 7be1dd732e434a509063f7a82dbefccc837da102! :smile:
